[package]
name = "s8pc-6"
version = "0.1.0"
edition = "2021"

# dependencies added to new project
[dependencies]
proconio = { version = "0.4.2", features = ["derive"] }

[profile.release]
lto = true
panic = 'abort'
